
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 22 23:11:35 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREQUAL = 42;
  public static final int INCREMENT = 49;
  public static final int CONST = 5;
  public static final int RSQUAREB = 10;
  public static final int NUMCONST = 13;
  public static final int NOTEQUAL = 40;
  public static final int GREATER = 41;
  public static final int LPAREN = 11;
  public static final int SEMI = 6;
  public static final int CONTINUE = 33;
  public static final int DECREMENT = 50;
  public static final int LESS = 43;
  public static final int FOR = 23;
  public static final int MINUS = 25;
  public static final int RPAREN = 12;
  public static final int LESSEQUAL = 44;
  public static final int EQUALTO = 39;
  public static final int COMMA = 7;
  public static final int CLASS = 17;
  public static final int DIV = 30;
  public static final int PLUS = 45;
  public static final int IF = 21;
  public static final int ABSTRACT = 19;
  public static final int EOF = 0;
  public static final int RETURN = 34;
  public static final int EQUAL = 8;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int MUL = 32;
  public static final int PERCENT = 48;
  public static final int ADD = 28;
  public static final int MOD = 31;
  public static final int BREAK = 24;
  public static final int IDENT = 14;
  public static final int VOID = 20;
  public static final int RCURLYB = 4;
  public static final int LCURLYB = 3;
  public static final int LSQUAREB = 9;
  public static final int ELSE = 22;
  public static final int READ = 35;
  public static final int POINT = 27;
  public static final int CHARCONST = 15;
  public static final int ANDLOGICAL = 38;
  public static final int ORLOGICAL = 37;
  public static final int BOOLCONST = 16;
  public static final int EXTENDS = 18;
  public static final int PROG = 2;
  public static final int DIVISION = 47;
  public static final int SUB = 29;
  public static final int MULTIPLICATION = 46;
  public static final int PRINT = 36;
}

